### ISSUE TITLE
aimbot doesnt work

### ISSUE THREAD

**Issue by gedissxd** [Jire/Overwatcheat#70]
i set everything up. build was successfull but when im in game aimbot doesnt work

**Comment by zixuan3** [comment]
Same issue

**Comment by Jire** [comment]
* Make sure you have the Interception driver installed
* Make sure you're using borderless-windowed mode
* Make sure you're using Magenta as your in-game enemy color

**Comment by zixuan3** [comment]
Hello, Jire. Could you please explain what the Interception driver is? I did not find any description of it in README. Thank you.

**Comment by zixuan3** [comment]
Now the script can run and capture the overwatch screen, but when I left click mouse, it does not move the aim at all. I've already set sensitivity to be same as in-game sensitivity, and the enemy color to magenta. I wonder why it isn't working at all...

**Comment by JohnSilver2077** [comment]
How to installed Interception driver thankyou

**Comment by gedissxd** [comment]
fixed in 3.1 update

**Comment by zixuan3** [comment]
I tried 3.1 update but it didn't work. The script can recognize Overwatch window, but it just did not work.

**Comment by JackMeds** [comment]
> 我尝试了3.1更新，但它没有工作。脚本可以识别监督窗口，但它只是没有工作。

Same issue

**Comment by JackMeds** [comment]
> I tried 3.1 update but it didn't work. The script can recognize Overwatch window, but it just did not work.

Same issue

**Comment by ovlizin** [comment]
> Make sure you have the Interception driver installed
Make sure you're using borderless-windowed mode
Make sure you're using Magenta as your in-game enemy color

i've done all of this and i'm still having issues someone please help
